[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyaptamer"
version = "0.0.1.dev0"
description = "Python library for aptamer simulation"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name="German Center for Open Source AI", email="info@gcos.ai"}
]

dependencies = [
    "openmm>=8.3.0,<8.4.0"
]

[project.optional-dependencies]
dev = [
    "ruff>=0.12.0",
    "pytest>=8.0.0",
    "pre-commit"
]

[tool.ruff]
line-length = 88
target-version = "py310"  # Match your `>=3.10` requirement

# Choose what to check for
lint.select = ["E", "F", "B", "I", "UP", "N", "C4"]

exclude = ["__pycache__", ".venv", "build", "dist", ".git"]

[tool.ruff.format]
quote-style = "double"
line-ending = "lf"
indent-style = "space"
docstring-code-format = true

[tool.setuptools.packages.find]
include = ["pyaptamer*"]
