[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyaptamer"
version = "0.0.1.dev0"
description = "Python library for aptamer simulation"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name="Matteo Pinna", email="nennomp@gmail.com" },
    { name="Your Name", email="your@email.com" },
]

dependencies = [
    "einops>=0.8.1",
    "jupyterlab>=4.2.6",
    "numpy>=2.0.2,<2.0.3",
    "openmm>=8.3.0,<8.4.0",
    "pandas>=2.2.3",
    "torch>=2.5.1",
    "torchvision>=0.20.1", 
]

[project.optional-dependencies]
dev = [
    "black>=25.0",
    "ruff>=0.12.0",
    "pytest>=8.0.0",
]