[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyaptamer"
version = "0.0.1.dev0"
description = "Python library for aptamer simulation"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name="Your Name", email="your@email.com" }
]

dependencies = [
    "openmm>=8.3.0,<8.4.0"
]

[project.optional-dependencies]
dev = [
    "ruff>=0.12.0",
    "black>=25.0",
    "pytest>=8.0.0"
]
