"""Tests for MoleculeLoader FASTA export functionality."""

import pytest

from pyaptamer.data.loader import MoleculeLoader


@pytest.fixture
def sample_fasta(tmp_path):
    """Create a sample FASTA file for testing."""
    fasta_content = (
        ">seq1 test protein 1\n"
        "ACDEFGHIKLMNPQRSTVWY\n"
        ">seq2 test protein 2\n"
        "MVLSPADKTNVKAAWGKVGA\n"
        ">seq3 test protein 3\n"
        "GHHEAELKPLATAALEHHHH\n"
    )
    fasta_path = tmp_path / "test_input.fasta"
    fasta_path.write_text(fasta_content)
    return fasta_path


class TestToFasta:
    """Tests for MoleculeLoader.to_fasta() method."""

    def test_basic_export(self, sample_fasta, tmp_path):
        """Test basic FASTA export produces a valid file."""
        loader = MoleculeLoader(str(sample_fasta))
        output_path = tmp_path / "output.fasta"
        n_written = loader.to_fasta(str(output_path))

        assert n_written == 3
        assert output_path.exists()

        # verify the output contains FASTA records
        content = output_path.read_text()
        assert content.count(">") == 3

    def test_round_trip(self, sample_fasta, tmp_path):
        """Test that export -> re-import preserves sequences."""
        loader = MoleculeLoader(str(sample_fasta))
        original_df = loader.to_df_seq()

        output_path = tmp_path / "round_trip.fasta"
        loader.to_fasta(str(output_path))

        # reload the exported file
        reloaded = MoleculeLoader(str(output_path))
        reloaded_df = reloaded.to_df_seq()

        # sequences should match
        original_seqs = sorted(original_df.iloc[:, 0].tolist())
        reloaded_seqs = sorted(reloaded_df.iloc[:, 0].tolist())
        assert original_seqs == reloaded_seqs

    def test_export_with_description(self, sample_fasta, tmp_path):
        """Test that description is written to each record."""
        loader = MoleculeLoader(str(sample_fasta))
        output_path = tmp_path / "described.fasta"
        loader.to_fasta(str(output_path), description="generated by pyaptamer")

        content = output_path.read_text()
        assert "generated by pyaptamer" in content

    def test_export_returns_count(self, sample_fasta, tmp_path):
        """Test that to_fasta returns the correct count."""
        loader = MoleculeLoader(str(sample_fasta))
        output_path = tmp_path / "count.fasta"
        n = loader.to_fasta(str(output_path))
        assert n == 3

    def test_export_creates_parent_dirs(self, sample_fasta, tmp_path):
        """Test export works when output_path parent exists."""
        loader = MoleculeLoader(str(sample_fasta))
        output_path = tmp_path / "subdir" / "output.fasta"
        output_path.parent.mkdir(parents=True)
        n = loader.to_fasta(str(output_path))
        assert n == 3
        assert output_path.exists()

    def test_single_sequence(self, tmp_path):
        """Test export with a single sequence."""
        fasta_content = ">single\nACDEFGHIKL\n"
        fasta_path = tmp_path / "single.fasta"
        fasta_path.write_text(fasta_content)

        loader = MoleculeLoader(str(fasta_path))
        output_path = tmp_path / "single_out.fasta"
        n = loader.to_fasta(str(output_path))

        assert n == 1
        content = output_path.read_text()
        assert "ACDEFGHIKL" in content
