name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
    types: [opened, synchronize]

  # Allows workflows to be manually triggered
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    name: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout step
        uses: actions/checkout@v5

      - name: python environment step
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: install pre-commit
        run: python3 -m pip install pre-commit

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | tr '\n' ' ')
          echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV

      - name: Print changed files
        run: |
          echo "Changed files: $CHANGED_FILES"

      - name: Run pre-commit on changed files
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            pre-commit run --color always --files $CHANGED_FILES --show-diff-on-failure
          else
            echo "No changed files to check."
          fi

      - name: check missing __init__ files
        run: bash build_tools/fail_on_missing_init_files.sh

  detect-notebooks-change:
    needs: code-quality
    name: detect change affecting notebooks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      notebooks: ${{ steps.check.outputs.notebooks }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Needed to access the full git history

      - name: Fetch main branch
        run: git fetch origin main

      - name: Check if examples, pyaptamer or pyproject.toml changed
        id: check
        run: |
          if git diff --quiet origin/main -- examples/ pyaptamer/ pyproject.toml; then
            echo "No notebook related changes"
            echo "notebooks=false" >> $GITHUB_OUTPUT
          else
            echo "Detected changes in notebooks or pyaptamer"
            echo "notebooks=true" >> $GITHUB_OUTPUT
          fi

  run-jupyter-notebooks:
    needs: code-quality
    if: ${{ needs.detect-notebooks-change.outputs.notebooks == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: git remote set-branches origin 'main'

      - run: git fetch --depth 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install package and dependencies
        run: |
          python -m pip install .[dev] --no-cache-dir
          python -m pip install jupyter nbconvert nbformat --no-cache-dir

      - name: Show dependencies
        run: python -m pip list

      - name: Show available branches
        run: git branch -a

      - name: Run jupyter notebooks
        run: |
          python -m pip install jupyter nbconvert ipykernel
          python -m ipykernel install --user --name=python3 --display-name "Python 3 (CI)"
          bash build_tools/run_all_notebooks.sh

  run-tests-no-extras:
    needs: code-quality
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - run: git remote set-branches origin 'main'

      - run: git fetch --depth 1

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install package and dependencies
        run: |
          python -m pip install .[dev] --no-cache-dir

      - name: Show dependencies
        run: python -m pip list

      - name: Show available branches
        run: git branch -a

      - name: Run tests
        run: |
          python -m pytest pyaptamer -p no:warnings
